/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BoardRouteImport } from './routes/board'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as HelpRouteImport } from './routes/help'
import { Route as InstallRouteImport } from './routes/install'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PairPrinterRouteImport } from './routes/pair-printer'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBackgroundRouteImport } from './routes/admin/background'
import { Route as AdminCenterRouteImport } from './routes/admin/center'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminFinancialsRouteImport } from './routes/admin/financials'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPatchesRouteImport } from './routes/admin/patches'
import { Route as AdminPosRouteImport } from './routes/admin/pos'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminServiceRouteImport } from './routes/admin/service'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminZonesRouteImport } from './routes/admin/zones'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PairPrinterRoute = PairPrinterRouteImport.update({
  id: '/pair-printer',
  path: '/pair-printer',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackgroundRoute = AdminBackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCenterRoute = AdminCenterRouteImport.update({
  id: '/center',
  path: '/center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialsRoute = AdminFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatchesRoute = AdminPatchesRouteImport.update({
  id: '/patches',
  path: '/patches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceRoute = AdminServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/board': typeof BoardRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/pair-printer': typeof PairPrinterRoute
  '/recover': typeof RecoverRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/background': typeof AdminBackgroundRoute
  '/admin/center': typeof AdminCenterRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/patches': typeof AdminPatchesRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/service': typeof AdminServiceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/board': typeof BoardRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/pair-printer': typeof PairPrinterRoute
  '/recover': typeof RecoverRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/background': typeof AdminBackgroundRoute
  '/admin/center': typeof AdminCenterRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/patches': typeof AdminPatchesRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/service': typeof AdminServiceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/board': typeof BoardRoute
  '/checkout': typeof CheckoutRoute
  '/help': typeof HelpRoute
  '/install': typeof InstallRoute
  '/login': typeof LoginRoute
  '/pair-printer': typeof PairPrinterRoute
  '/recover': typeof RecoverRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/background': typeof AdminBackgroundRoute
  '/admin/center': typeof AdminCenterRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/patches': typeof AdminPatchesRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/service': typeof AdminServiceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/board'
    | '/checkout'
    | '/help'
    | '/install'
    | '/login'
    | '/pair-printer'
    | '/recover'
    | '/verify-2fa'
    | '/admin/background'
    | '/admin/center'
    | '/admin/customers'
    | '/admin/financials'
    | '/admin/menu'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/patches'
    | '/admin/pos'
    | '/admin/rewards'
    | '/admin/service'
    | '/admin/settings'
    | '/admin/zones'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/board'
    | '/checkout'
    | '/help'
    | '/install'
    | '/login'
    | '/pair-printer'
    | '/recover'
    | '/verify-2fa'
    | '/admin/background'
    | '/admin/center'
    | '/admin/customers'
    | '/admin/financials'
    | '/admin/menu'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/patches'
    | '/admin/pos'
    | '/admin/rewards'
    | '/admin/service'
    | '/admin/settings'
    | '/admin/zones'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/board'
    | '/checkout'
    | '/help'
    | '/install'
    | '/login'
    | '/pair-printer'
    | '/recover'
    | '/verify-2fa'
    | '/admin/background'
    | '/admin/center'
    | '/admin/customers'
    | '/admin/financials'
    | '/admin/menu'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/patches'
    | '/admin/pos'
    | '/admin/rewards'
    | '/admin/service'
    | '/admin/settings'
    | '/admin/zones'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BoardRoute: typeof BoardRoute
  CheckoutRoute: typeof CheckoutRoute
  HelpRoute: typeof HelpRoute
  InstallRoute: typeof InstallRoute
  LoginRoute: typeof LoginRoute
  PairPrinterRoute: typeof PairPrinterRoute
  RecoverRoute: typeof RecoverRoute
  Verify2faRoute: typeof Verify2faRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair-printer': {
      id: '/pair-printer'
      path: '/pair-printer'
      fullPath: '/pair-printer'
      preLoaderRoute: typeof PairPrinterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/background': {
      id: '/admin/background'
      path: '/background'
      fullPath: '/admin/background'
      preLoaderRoute: typeof AdminBackgroundRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/center': {
      id: '/admin/center'
      path: '/center'
      fullPath: '/admin/center'
      preLoaderRoute: typeof AdminCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financials': {
      id: '/admin/financials'
      path: '/financials'
      fullPath: '/admin/financials'
      preLoaderRoute: typeof AdminFinancialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patches': {
      id: '/admin/patches'
      path: '/patches'
      fullPath: '/admin/patches'
      preLoaderRoute: typeof AdminPatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service': {
      id: '/admin/service'
      path: '/service'
      fullPath: '/admin/service'
      preLoaderRoute: typeof AdminServiceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBackgroundRoute: typeof AdminBackgroundRoute
  AdminCenterRoute: typeof AdminCenterRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFinancialsRoute: typeof AdminFinancialsRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPatchesRoute: typeof AdminPatchesRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminServiceRoute: typeof AdminServiceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBackgroundRoute: AdminBackgroundRoute,
  AdminCenterRoute: AdminCenterRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFinancialsRoute: AdminFinancialsRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPatchesRoute: AdminPatchesRoute,
  AdminPosRoute: AdminPosRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminServiceRoute: AdminServiceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminZonesRoute: AdminZonesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BoardRoute: BoardRoute,
  CheckoutRoute: CheckoutRoute,
  HelpRoute: HelpRoute,
  InstallRoute: InstallRoute,
  LoginRoute: LoginRoute,
  PairPrinterRoute: PairPrinterRoute,
  RecoverRoute: RecoverRoute,
  Verify2faRoute: Verify2faRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
